stages:
  - build
  - test
  - deploy

# Define the build stage
build:
  stage: build
  image: node:14
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build

# Define the test stage
test:
  stage: test
  image: node:14
  script:
    - npm install
    - npm run test

# Define the deploy stage
deploy:
  stage: deploy
  image: node:14
  script:
    - npm install -g serve
    - serve -s build
  only:
    - main
