stages:
  - build
  - test
  - deploy

before_script:
  - echo "Setting up environment"
  - node -v
  - npm -v

build:
  stage: build
  image: node:14
  script:
    - echo "Installing dependencies"
    - npm install
    - echo "Building project"
    - npm run build
  artifacts:
    paths:
      - build
  only:
    - main

deploy:
  stage: deploy
  image: node:14
  script:
    - echo "Deploying application"
    - npm install -g serve
    - serve -s build
  only:
    - main
